
services:
  nginx:
    build:
      context: ..
      dockerfile: ./docker/nginx/nginx.localarea.Dockerfile
    container_name: nginx
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/certs:/etc/nginx/certs
      - ./nginx/nginx.localarea.conf.template:/etc/nginx/nginx.localarea.conf.template
      - avahi-logs:/avahi
    env_file:
      - .env
    entrypoint: /etc/nginx/entrypoint.sh
    depends_on:
      - avahi
      - homepage-app
    networks:
      - full-stack-network

  avahi:
    image: flungo/avahi
    container_name: avahi
    network_mode: host
    restart: always
    env_file:
      - .env
    volumes:
      - avahi-logs:/avahi
      - ./avahi-config:/etc/avahi
    hostname: '${AVAHI_HOSTNAME}'
    command: >
      sh -c "
        apk add --no-cache gettext &&
        rm -rf /avahi/* &&
        envsubst < /etc/avahi/avahi-daemon.conf.template > /etc/avahi/avahi-daemon.conf &&
        /usr/sbin/avahi-daemon > /avahi/avahi.log 2>&1 &&
        tail -f /dev/null"

  postgres:
    image: postgres:13.5
    container_name: postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_DB: '${POSTGRES_DB}'
    volumes:
      - localareanetwork-production-postgres:/var/lib/postgresql/data
    ports:
      - '5435:5432'
    networks:
      - full-stack-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 20s
      timeout: 5s
      retries: 10

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    env_file:
      - .env
    ports:
      - '8080:8080'
    networks:
      - full-stack-network
    depends_on:
      - postgres
    environment:
      ADMINER_DEFAULT_SERVER: 'postgres'
      ADMINER_DEFAULT_DB: '${POSTGRES_DB}'
      ADMINER_DEFAULT_USER: '${POSTGRES_USER}'
      ADMINER_DEFAULT_PASSWORD: '${POSTGRES_PASSWORD}'

  nestjs:
    container_name: nestjs
    build:
      context: ..
      dockerfile: docker/nest.Dockerfile
    env_file:
      - ../${BACKEND_ENV_FILE:-apps/backend/.env.localareanetwork}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - full-stack-network
    volumes:
      - avahi-logs:/avahi

  homepage-app:
    container_name: homepage-app
    build:
      context: ..
      dockerfile: docker/homepage-app.Dockerfile
    env_file:
      - ../${FRONTEND_ENV_FILE:-apps/frontend/homepage-app/.env.localareanetwork}
    depends_on:
      - nestjs
    networks:
      - full-stack-network
    volumes:
      - avahi-logs:/avahi

  hostname-printer:
    image: ubuntu:22.04
    container_name: hostname-printer
    restart: 'no'
    networks:
      - full-stack-network
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      avahi:
        condition: service_started
    volumes:
      - ./scripts:/usr/local/bin
      - avahi-logs:/avahi
    command:
      - sh
      - -c
      - |
        chmod +x /usr/local/bin/hostname-printer.sh
        /usr/local/bin/hostname-printer.sh

  service-watcher:
    build:
      context: ..
      dockerfile: ./docker/service-watcher.Dockerfile
    container_name: service-watcher
    restart: on-failure
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      avahi:
        condition: service_started
    networks:
      - full-stack-network
    volumes:
      - avahi-logs:/avahi

volumes:
  localareanetwork-production-postgres:
  avahi-logs:

networks:
  full-stack-network:
    driver: bridge
